config/routes.rb
Rails.application.routes.draw do
  root to: "groceries#index"

  resources :groceries
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/grocery.rb
class Grocery < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery unless: -> { request.format.json? }

  def feature_open?(feature)
    rcurtain = Rcurtain.instance
    rcurtain.opened? feature
  end
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController

  def index
    @groceries = Grocery.all
    @new_button = feature_open?('grocery-button')

    respond_to do |format|
      format.html
      format.json { render json: @groceries }
    end
  end

  def new

  end

  def create
    params.permit!

    @grocery = Grocery.new(params[:grocery])
    @grocery.save

    redirect_to '/'
  end

  def destroy
    @grocery = Grocery.find(params[:id])
    @grocery.destroy

    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/helpers/grocery_helper.rb
module GroceryHelper
end

app/views/groceries/index.html.erb
<% if @groceries.blank? %>
  <h5> Start adding items to your grocery </h5>
<% end %>

<ul class="collection">
  <% @groceries.each do |grocery| %>
    <li class="collection-item">
      <%= grocery.quantity %> - <%= grocery.name %>
      <%= link_to grocery_path(grocery), method: :delete, data: { confirm: 'Remove item from grocery list?' }, class: 'right' do %>
        <i class="material-icons">delete</i>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @new_button %>
  <%= link_to ("<i class=\"material-icons\">add</i>").html_safe, new_grocery_path, class: "btn-floating waves-effect waves-light right-align right blue" %>
<% else %>
  <%= link_to 'Add item', new_grocery_path, class: "waves-effect waves-light btn white-text right blue" %>
<% end %>

app/views/groceries/new.html.erb
<h5> Add item to Grocery List </h5>

<%= form_with scope: :grocery, url: groceries_path do |form| %>
  <div class="row">
    <div class="col s10">
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
    </div>

    <div class="col s2">
      <p>
        <%= form.label :quantity %><br>
        <%= form.number_field :quantity %>
      </p>
    </div>

  </div>
  <p>
    <%= form.submit "Add to list", class: "waves-effect waves-light btn white-text blue right" %>
  </p>
<% end %>

app/views/grocery/new.html.erb
<h3> Add item to Grocery List </h3>

<%= form_with scope: :grocery do |form| %>
  <div class="row">
    <div class="col s10">
      <p>
        <%= form.label :name %><br>
        <%= form.text_field :name %>
      </p>
    </div>

    <div class="col s2">
      <p>
        <%= form.label :quantity %><br>
        <%= form.text_field :quantity %>
      </p>
    </div>

  </div>
  <p>
    <%= form.submit class: "waves-effect waves-light btn" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroceryList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper blue darken-1">
        <div class="row center">
          <b>My Grocery List</b>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row">
        <div class="col-md-3">
        </div>
        <div class="col-md-6">
          <%= yield %>
        </div>
        <div class="col-md-3">
        </div>
      </div>
    </div>
  </body>
</html>